def puts_lyric_item
  lyrics_array = ["“Emancipate yourselves from mental slavery.
None but ourselves can free our minds.” ― Bob Marley", 
    "“Don't criticize what you can't understand.” ― Bob Dylan", 
    "“you're an expert at sorry and keeping the lines blurry” ― Taylor Swift", 
    "“I get by with a little help from my friends.” ― John Lennon", 
    "“When pain brings you down, don't be silly, don't close your eyes and cry, you just might be in the best position to see the sunshine.” ― Alanis Morissette", 
    "“You have every right to a beautiful life.” ― Selena Gómez", 
    "“Lose your dream, you lose your mind.” ― Rolling Stones", 
    "“sleeping all these demons away” ― Ella Henderson ", 
    "“I'll be the beauty queen in tears” ― Lorde", 
    "“Don’t turn your back on me. I won’t be ignored” – Linkin Park", 
    "“It's my party and I'll cry if I want to!” – Melanie Martinez", 
    "“it's a new artform” ― Lorde", 
    "“laughing 'til our ribs get tough” ― Lorde", 
    "“I am not a white teeth teen.” ― Lorde", 
    "“Glory and Gore go hand in hand” ― Lorde" , 
    "“I'm lying in the ocean, singing your song.” ― Lana del Ray", 
    "“and there is no remedy for memory” ― Lana del Rey", 
    "“We're the wild ones. Curious fools. Trapped in the flume.” ― Baharia",
    "“war inside my mind, drowning in the tides.” ― Baharia",
    "“you're the magician's assitant in their dreams” ― Vance Joy",
    "“running down to the riptide.” ― Vance Joy",
    "“be my great escape 'til we fade away.” ― Baharia",
    "“in silent screams. in wildest dreams. I never dreamed of this.” ― Taylor Swift",
    "“raised by wolves, we howl to the moon.” ― Baharia",
    "“it's like a dark paradise.” ― Lana del Rey",
    "“now I need someone to breathe me back to life.” ― Shawn Mendes",
    "“you watch me beat until I can't breathe.” ― Shawn Mendes",
    "“got a feeling that I'm going under.” ― Shawn Mendes",
    "“Take me to wonderland”  ― Natalia Kills",
    "“we found wonderland.”  ― Taylor Swift",
    "“they say it's easy to leave you behind. I don't want to try.”  ― Years & Years",
    "“I was a king under your control.”  ― Years & Years ",
    "“I want to feel like you've let me go. So let me go”  ― Years & Years",
    "“Somewhere Only We Know”  ― Keane",
    "“I feel like I'm glued on tight to this Carousel”  ― Melanie Martinez",
    "“Chasing after you is like a fairytale”  ― Melanie Martinez",
    "“You sprinkled stardust on my pillowcase”  ― Echosmith",
    "“I'm in over my head.”  ― FLETCHER",
    "“like thunder needs the rain”  ― FLETCHER",
    "“Too late to leave these walls. This castle's been surrounded. Won't stay to watch it fall around us”  ― FLETCHER",
    "“Watch me put my war paint on, my war paint on”  ― FLETCHER",
    "“Now we're lost somewhere in outer space”  ― Halsey",
    "“Scream in the name of a foreigner's God ”  ― Hozier",
    "“We gladiate, but I guess we are really fighting ourselves”  ― Lorde",
    "“let your colors bleed & blend with mine”  ― Of Monsters and Men",
    "“Freshly disowned in a frozen devotion”  ― Hozier",
    "“Only then I am human. Only then I am clean.”  ― Hozier",
    "“I can't find you in the dark”  ― Cathedrals",
    "“When I run to the sea till sun shines”  ― Cathedrals",
    "“Let's get out of this town babe, we're on fire”  ― Lana Del Rey",
    "“but now's our curtain call”  ― Kygo",
    "“and I will haunt you like a ghost”  ― Margot and the Nuclear So & So's",
    "“and I wrote this on an airplane where people looked like ants.”  ― Margot and the Nuclear So & So's",
    "'music is a universal language'  ― Halsey",
    "“Syncapate my skin to your heart beating”  ― Selena Gomez "]
  lyrics_array[rand(lyrics_array.count)]
end

def puts_nature_item
  nature_array = ["the best thing one can do when it's raining is to let it rain.",
    "Just living is not enough... one must have sunshine, freedom, and a little flower.", 
    "there are always flowers for those who want to see them",
    "some people walk in the rain, others just get wet",
    "light in nature creates the movement of colors",
    "Rain is grace; rain is the sky descending to the earth; without rain, there would be no life",
    "stars can't shine without darkness",
    "His hat was old, his coat worn, the water passed through his shoes and the stars through his soul.",
    "Watch the stars, and see yourself running with them.",
    "Magic exists. Who can doubt it, when there are rainbows and wildflowers, the music of the wind and the silence of the stars?",
    "in sunlight, starlight, and moonlight.",
    "running to the river", 
    "reach for the sky, and you'll land on the moon.",
    "Sunset is still my favorite color, and rainbow is second.",
    "Behind every cloud is another cloud, and I love that.",
    "Nature always wears the colors of the spirit.",
    "Wherever you go, no matter what the weather, always bring your own sunshine.",
    "No snowflake ever falls in the wrong place.",
    "And as we wind on down the road...",
    "when the fireworks soar above",
    "typos are for kool kids"]
  nature_array[rand(nature_array.count)]
end

def puts_love_item  
  love_array = ["“It's better to be hated for what you are than be loved for what you aren't.” ― André Gide,",
    "“You've gotta dance like there's nobody watching, Love like you'll never be hurt, Sing like there's nobody listening, and live like it's heaven on earth.” ― William W. Purkey", 
    "“You know you're in love when you can't fall asleep because reality is finally better than your dreams.” ― Dr. Seuss", 
    "“Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.” ― MLK Jr.", 
    "“You don't love someone because they're perfect, you love them in spite of the fact that they're not.” ― Jodi Picoult,",
    "“It's better to have loved and lost, than never to have loved at all.” ― Alfred Lord Tennyson",
    "“all through history, the way of truth and love has always won. There have been tyrants, but in the end, they always fall.” ― Mahatma Gandhi",
    "“One is loved because one is loved. No reason is needed for loving.”― Paulo Coelho",
    "“Where there is love, there is life.” ― Mahatma Gandhi",
    "“What's meant to be will always find a way” ― Trisha Yearwood",
    "Anyone who has loved has been touched by magic. It is such a simple and such an extraordinary part of the lives we live.",
    "Within the work of hatred, we find the world of love.",
    "fade me.",
    "I was lovely once, but he never loved me once",
    "I knew my feelings for you were real when I spent more time thinking about you than worrying about myself.",
    "You are every reason, every hope and every dream I've ever had.",
    "Love yourself first, because you are most important.",
    "Be confident!",
    "Follow love and it will flee, flee love and it will follow.",
    "The rose speaks of love silently, in a language known only to the heart."]  
  love_array[rand(love_array.count)]
end

def puts_philosophy_item
  philosophy_array = ["This is my simple religion. There is no need for temples; no need for complicated philosophy. Our own brain, our own heart is our temple; the philosophy is kindness.",
    "I have a simple philosophy: Fill what's empty. Empty what's full. Scratch where it itches.",
    "The philosophy of the school room in one generation will be the philosophy of government in the next.",
    "You can be creative in anything - in math, science, engineering, philosophy - as much as you can in music or in painting or in dance." "Simplicity is the ultimate sophistication.",
    "Just live.",
    "Eventually, you might see the good in 'goodbye'",
    "I can't go back to yesterday because I was a different person then.", 
    "No matter how many plans you make or how much in control you are, life is always winging it.",
    "A ship is always safe at the shore, but that is not what it is built for.",
    "If you live it, you should love it!",
    "We all have two lives, but the second starts when we realize we only have one.",
    "The man on top of the mountain didn't fall there.", 
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. — Albert Einstein",
    "Be the change that you wish to seek in yourself.",
    "Go to heaven for the climate and hell for the company. — Benjamin Franklin Wade",
    "Have you ever noticed how ‘What the hell’ is always the right decision to make? — Terry Johnson (Insignificance)",
    "Man is the only creature who refuses to be what he is. — Albert Camus",
    "If a cluttered desk is a sign of a cluttered mind, of what, then, is an empty desk a sign? — Albert Einstein",
    "Never let your sense of morals prevent you from doing what is right. — Isaac Asimov",
    "Happiness is infectious & laughter is contagious",
    "life is boundless.",
    "find a passion and love it endlessly.",
    "create yourself.",
    "Be young, be dope, be proud -Lana Del Rey", 
    "nothing is worse than realizing it was national ice-cream day after it's over.",
    "life's too short to not always try and be happy.",
    "never stop learning on the road to wisdom!",
    "We are the leaders of the not coming back.",
    "It is scientifically proven that one person's emoitons affet all those around them. Be happy and make everyone happy.",
    "Even if you just try to smile, trying is better than giving up.",
    "Some of the best advice I've ever gotten is that you'll still make it even if you fake it. So smile. Laugh. Try to just be happy, and eventually you won't have to even try anymore, because it will just be natural. :)", 
    "Knock on the sky and listen to the sound.",
    "Tomorrow always comes, and today is never yesterday.",
    "You can see a lot by just looking.",
    "The opposite of a correct statement is a false statement. But the opposite of a profound truth may well be another profound truth.",
    "There are things I have wanted so long that I would only consent to have them if I could keep wanting them.",
    "Eggs cannot be unscrambled!",
    "I want everything to be perfect, but where the hell is the fun in that?",
    "The dreams that are meant to, WILL come true.",
    "Wish on every shooting star, on every birthday candle, and every 11:11.",
    "it's simple, but: be you.",
    "shirt inside out & life upside down",
    "become a complex person."]
  philosophy_array[rand(philosophy_array.count)]
end 